export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_VERIFY = 'AUTH_VERIFY';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const INIT_TENANT_CONFIG = 'INIT_TENANT_CONFIG';
export const INIT_COUNTRIES = 'INIT_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const INIT_HOME_COLLECTIONS = 'INIT_HOME_COLLECTIONS';
export const SET_HOME_COLLECTIONS = 'SET_HOME_COLLECTIONS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

export const INIT_PRODUCT_DETAILS = 'INIT_PRODUCT_DETAILS';
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const FETCH_PRODUCT_DETAILS_FAILED = 'FETCH_PRODUCT_DETAILS_FAILED';

export const INIT_STORE_DETAILS = 'INIT_STORE_DETAILS';
export const SET_STORE_DETAILS = 'SET_STORE_DETAILS';
export const FETCH_STORE_DETAILS_FAILED = 'FETCH_STORE_DETAILS_FAILED';

export const INIT_LISTING = 'INIT_LISTING';
export const SET_LISTING = 'SET_LISTING';
export const FETCH_LISTING_FAILED = 'FETCH_LISTING_FAILED';

export const INIT_STORE_LISTS = 'INIT_STORE_LISTS';
export const SET_STORE_LISTS = 'SET_STORE_LISTS';
export const FETCH_STORE_LISTS_FAILED = 'FETCH_STORE_LISTS_FAILED';

export const SET_CATEGORY_LISTS = 'SET_CATEGORY_LISTS';
export const INIT_CATEGORY_LISTS = 'INIT_CATEGORY_LISTS';
export const FETCH_CATEGORY_LISTS_FAILED = 'FETCH_CATEGORY_LISTS_FAILED';

export const INIT_CREATE_STORE = 'INIT_CREATE_STORE';
export const CREATE_STORE_FAILED = 'CREATE_STORE_FAILED';
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';

export const SUCCESS_TENANT_CONFIG = 'SUCCESS_TENANT_CONFIG';

export const FAILED_TENANT_CONFIG = 'FAILED_TENANT_CONFIG';

export const INIT_GROUP_DETAILS = 'INIT_GROUP_DETAILS';
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const FETCH_GROUP_DETAILS_FAILED = 'FETCH_GROUP_DETAILS_FAILED';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const INIT_CREATE_GROUP = 'INIT_CREATE_GROUP';

export const SET_SUPPLIER_LISTS = 'SET_SUPPLIER_LISTS';
export const INIT_SUPPLIER_LISTS = 'INIT_SUPPLIER_LISTS';
export const FETCH_SUPPLIER_LISTS_FAILED = 'FETCH_SUPPLIER_LISTS_FAILED';

export const START_PRODUCT_LIKE_DISLIKE = 'START_PRODUCT_LIKE_DISLIKE';
export const SET_PRODUCT_LIKE_DISLIKE = 'SET_PRODUCT_LIKE_DISLIKE';
export const FAILED_PRODUCT_LIKE_DISLIKE = 'FAILED_PRODUCT_LIKE_DISLIKE';

export const POST_STORE_FOLLOW_REQUEST = 'POST_STORE_FOLLOW_REQUEST';
export const POST_STORE_FOLLOW_SUCCESS = 'POST_STORE_FOLLOW_SUCCESS';
export const POST_STORE_FOLLOW_FAILED = 'POST_STORE_FOLLOW_FAILED';
