export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_VERIFY = 'AUTH_VERIFY';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';



export const INIT_TENENT_CONFIG = 'INIT_TENENT_CONFIG';
export const INIT_COUNTRIES = 'INIT_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const INIT_HOME_COLLECTIONS = 'INIT_HOME_COLLECTIONS';
export const SET_HOME_COLLECTIONS = 'SET_HOME_COLLECTIONS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

export const INIT_PRODUCT_DETAILS = 'INIT_PRODUCT_DETAILS';
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const FETCH_PRODUCT_DETAILS_FAILED = 'FETCH_PRODUCT_DETAILS_FAILED';


export const INIT_STORE_DETAILS = 'INIT_STORE_DETAILS';
export const SET_STORE_DETAILS = 'SET_STORE_DETAILS';
export const FETCH_STORE_DETAILS_FAILED = 'FETCH_STORE_DETAILS_FAILED';

export const INIT_LISTING = 'INIT_LISTING';
export const SET_LISTING = 'SET_LISTING';
export const FETCH_LISTING_FAILED = 'FETCH_LISTING_FAILED';


export const INIT_STORE_LISTS = 'INIT_STORE_LISTS';
export const SET_STORE_LISTS = 'SET_STORE_LISTS';
export const FETCH_STORE_LISTS_FAILED = 'FETCH_STORE_LISTS_FAILED';